modLoader="javafml"
loaderVersion="[33,)"
license="MIT"
issueTrackerURL="https://github.com/EwyBoy/Cultivated-Tech/issues"

[[mods]]
modId="cultivatedtech"
displayName="Cultivated-Tech"
version="${file.jarVersion}"
authors="Ewy"
credits="Shutout to my Twitch chat that reminded me to spell credits with an R"
description='''
A small mod for people with small penises
'''

[[dependencies.cultivatedtech]]
    modId="bibliotheca"
    mandatory=true
    versionRange="[1.4.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.cultivatedtech]]
    modId="forge"
    mandatory=true
    versionRange="[33.0.+,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.cultivatedtech]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.2]"
    ordering="NONE"
    side="BOTH"